### PR TITLE
Added stars and license

### PR DESCRIPTION
**Pull request by justanotheranonymoususer**

### CODE REVIEW

**Comment by dbohdan** [comment]
Sorry, but I think this will not make the catalog more useful.  Every project contributed so far has been either BSD or MIT.  If exceptions appear, a visual marker can be added just for them.  The number of stars makes little difference for projects like this.  They do not have a complex system of potentially interacting CSS classes to maintain, and you can assess their quality visually.

**Comment by dbohdan** [comment]
Actually, I'd merge a PR adding the star count.  However, it shouldn't be in the table on contents.  Maybe put the star count badge above the repo and demo link for each project?

**Comment by justanotheranonymoususer** [comment]
The idea was to see everything at a glance. I did it for myself to find the top libraries. Number of stars has some correlation about the maturity of the project, even thought it's not perfect. I would be hesitant to use a project with two stars in production.

**Comment by dbohdan** [comment]
I agree that the number of stars correlates with project maturity to a degree.  I think just it is less informative for this particular kind of project (small, a fairly niche target audience, CSS).  However, adding GitHub stats is worth a try.  Added in db19fe4.

**Pull request closed without merging**
